### ISSUE TITLE
Unresolved external references when including midifile with my progam..

### ISSUE THREAD

**Issue by hardwiredstudios** [craigsapp/midifile#10]
Hi, maybe a rookie question but i want to use the midifile source code and include it in a project but i'm having difficulties with 8 unresolved external references, similar to this one:

```
Severity	Code	Description	Project	File	Line
Error	LNK2019	unresolved external symbol "public: int __thiscall MidiFile::addEvent(int,int,class std::vector<unsigned char,class std::allocator<unsigned char> > &)" (?addEvent@MidiFile@@QAEHHHAAV?$vector@EV?$allocator@E@std@@@std@@@Z) referenced in function "void __cdecl CREATE_MIDI(void)" (?CREATE_MIDI@@YAXXZ)	SPMA - Assignment 1 - 4591930 EPM	C:\Users\Paul\Desktop\Uni Stuff - YEAR 2\SOFTWARE PROGRAMMING\Assignments\Assignment 1\SPMA - Assignment 1 - 4591930 EPM\Main.obj	1
```

I want my midifile to be a subfolder in my project so i have #include "midifile/include/MidiFile.h" in my code and the following code i adapted a bit from the create midi files section of the midifile app on here: https://github.com/craigsapp/midifile/blob/master/src-programs/createmidifile.cpp

```C++
// FUNCTION: CREATE MIDI DATA..
void CREATE_MIDI()
{
	MidiFile outputfile;        // CREATE AN EMPTY MIDI FILE WITH ONE TRACK..
	outputfile.absoluteTicks();  // TIME INFO STORED AS ABSOLUTE TIME..
	outputfile.addTrack(number_of_melodies -1);     // ADD ALL CURRENT MELODIES (-1 AS WE ALREADY HAVE ONE TRACK)..
	vector<uchar> midievent;     // TEMP STORAGE FOR MIDI EVENTS..
	midievent.resize(3);        // SET THE ARRAY SIZE TO 3 BYTES..
	int tpq = 120;              // default value in MIDI file is 48
	outputfile.setTicksPerQuarterNote(tpq);

	// store a melody line in track 1 (track 0 left empty for conductor info)
	int i = 0;
	double actiontime = 0;      // temporary storage for MIDI event time
	midievent[2] = 64;       // store attack/release velocity for note command..

	// FOR: LOOP AROUND NUMBER OF MELODIES..
	for (counter i = 0; i < number_of_melodies; ++i)
	{
		// FOR: LOOP ROUND NUMBER OF NOTES IN EACH MELODY..
		for (counter j = 0; j < noteOUT.note_value[i].size(); ++j)
		{
			midievent[i] = 0x90;     // STORE 'NOTE-ON' COMMAND (ON MIDI CHANNEL 1)..
			midievent[i+1] = noteOUT.midi_number[i][j];	// ADD MELODY MIDI NUMBER INFO..
			outputfile.addEvent(1, actiontime, midievent);	// APPEND THE MIDI EVENT TO THE FILE..
			actiontime += tpq * noteOUT.note_length_MS[i][j];		// CALCULATE TIMINGS AND APPEND FOR EACH NOTE..		
			midievent[i] = 0x80;     // STORE 'NOTE-OFF' COMMAND (ON MIDI CHANNEL 1)..
			outputfile.addEvent(1, actiontime, midievent);	// APPEND THE MIDI EVENT TO THE FILE..
			actiontime = 0;	//RESET ACTIONTIME..
		}
		// END FOR..
	}
	// END FOR..

	outputfile.sortTracks();         // ORGANISE DATA INTO CORRECT ORDER..
	outputfile.write(fileX.full_path_midi); // WRITE STANDARD MIDI FILE..
}
// END FUNCTION..
```

My program won't compile, I can't interperet the error messages other than they seem to mention spme of the midifile functions, like they're undefined or something, so something is amiss in my folder structures or implemenation into my program.

Any ideas what could be causing this? And how am i supposed to properly include and be able to use the midifile stuff?

Thanks,

Paul..

**Comment by kirbyfan64** [comment]
You need to link with libmidifile.

**Comment by hardwiredstudios** [comment]
Hey Kirbyfan, ok cool. How do i do that? I'm very new to c++ so apologies if this is an easy question

**Comment by hardwiredstudios** [comment]
I have tried following the guide on the midifile front page: http://midifile.sapp.org/

I have tried the guide on the main page on here: https://github.com/craigsapp/midifile

but no console, either powershell, bash or cmd accept "make" as a command. Where do i type "make library"? I've never used git before so have no clue on it yet.

**Comment by kirbyfan64** [comment]
You use Visual Studio, right? I don't think the build instructions work with Visual Studio... I'll see if I can help! Hold on a sec...

**Comment by hardwiredstudios** [comment]
Hey Ryan, yeah i'm using VS2015 and if it's matters, its a WIn32 console app i'm writing

**Comment by kirbyfan64** [comment]
Try this:

- Create a new file in the midifile source directory named `midifile.vcxproj`. Enter the following inside:

```xml
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.default.props" />
  <PropertyGroup>
    <ConfigurationType>Application</ConfigurationType>
    <PlatformToolset>v140</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ItemGroup>
    <ClCompile Include="src-library/MidiFile.cpp" />
    <ClCompile Include="src-library/MidiEvent.cpp" />
    <ClCompile Include="src-library/MidiMessage.cpp" />
    <ClCompile Include="src-library/MidiEventList.cpp" />
    <ClCompile Include="src-library/Binasc.cpp" />
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="include/MidiFile.h" />
    <ClInclude Include="include/MidiEvent.h" />
    <ClInclude Include="include/MidiMessage.h" />
    <ClInclude Include="include/MidiEventList.h" />
    <ClInclude Include="include/Binasc.h" />  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Targets" />
</Project>
```

Now open up the Visual Studio Command Prompt and enter:

```
cd directory_where_you_saved_the_file
msbuild
```

Tell me if it works!

**Comment by hardwiredstudios** [comment]
Ok brilliant, i'm trying it now :)

When i create a new project, i have nothing to paste the code into. Do i need to add a main.cpp or something? The .vcxproj file isn't editable is it? How do i create and edit a .vcxproj file without creating a new project in visual studio?

**Comment by kirbyfan64** [comment]
Try using Notepad.

**Comment by hardwiredstudios** [comment]
Right done that. Now opened up a visual studio command window. It does not recognise "cd"

**Comment by kirbyfan64** [comment]
Not the Command Window, the Command Prompt! See the section labeled "To open a Developer Command Prompt window" in https://msdn.microsoft.com/en-us/library/f35ctcxw.aspx

**Comment by hardwiredstudios** [comment]
Ah ok, sorry. Ok i tried that but it apparently failed. See the screen shot below:
![msbuild command prompt for vs 2015 - fail](https://cloud.githubusercontent.com/assets/16420301/12067087/7cc34ee4-afeb-11e5-8b0f-49e499427a99.jpg)

**Comment by kirbyfan64** [comment]
Can you try entering `echo %PLATFORM%` at the prompt and post the output?

**Comment by hardwiredstudios** [comment]
It just says MCD

**Comment by kirbyfan64** [comment]
Can you try running `set "PLATFORM="` before `msbuild`?

**Comment by hardwiredstudios** [comment]
Ok, tried that but i get this now (in 2 screenshots)..

Thank you so much for bearing with me on this one :)

![msbuild command prompt for vs 2015 - fail2a](https://cloud.githubusercontent.com/assets/16420301/12068210/bf718994-b000-11e5-8d48-807c76d0da3b.jpg)

![msbuild command prompt for vs 2015 - fail2b](https://cloud.githubusercontent.com/assets/16420301/12068211/bf7259dc-b000-11e5-990a-d92879049942.jpg)

**Comment by kirbyfan64** [comment]
Could you try replacing all the instances of `ClCompile` in `midifile.vcxproj` with `ClCompile AdditionIncludeDirectories="include"`?

**Comment by hardwiredstudios** [comment]
Hey Ryan, happy new year :)

So if i replace all lines like:
<ClCompile Include="src-library/MidiFile.cpp" />

...with:
<ClCompile AdditionIncludeDirectories="include" />

????

Tried it and now get this:

![msbuild command prompt for vs 2015 - fail3](https://cloud.githubusercontent.com/assets/16420301/12071141/a6956678-b093-11e5-9957-0f2136fe316a.jpg)

**Comment by kirbyfan64** [comment]
Haha, I'm an idiot. I was supposed to say `AdditionalIncludeDirectories`, not `AdditionIncludeDirectories`. Could you try it again?

Sorry about that...

**Comment by hardwiredstudios** [comment]
No worries, no need to apologise. I edited the vcxproj and that but still no :(
I did in vs console prompt:

cd my_directory
set "PLATFORM="
msbuild

and got this:
![msbuild command prompt for vs 2015 - fail4](https://cloud.githubusercontent.com/assets/16420301/12072286/3f968d44-b0cf-11e5-8af1-4ed8a0cef856.jpg)

**Comment by kirbyfan64** [comment]
What if you try replacing the contents of `midifile.vcxproj` with:

```xml
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.default.props" />
  <PropertyGroup>
    <ConfigurationType>Application</ConfigurationType>
    <PlatformToolset>v140</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ItemGroup>
    <ClCompile Include="src-library/*.cpp">
      <AdditionalIncludeDirectories>include</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="include/MidiFile.h" />
    <ClInclude Include="include/MidiEvent.h" />
    <ClInclude Include="include/MidiMessage.h" />
    <ClInclude Include="include/MidiEventList.h" />
    <ClInclude Include="include/Binasc.h" />  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Targets" />
</Project>
```

**Comment by hardwiredstudios** [comment]
Ooh it did something for a while then no hahaha. I got these (in 2 screen shots):

![msbuild command prompt for vs 2015 - fail5a](https://cloud.githubusercontent.com/assets/16420301/12072514/c927102e-b0d9-11e5-862c-2102feaba572.jpg)
![msbuild command prompt for vs 2015 - fail5b](https://cloud.githubusercontent.com/assets/16420301/12072513/c926ada0-b0d9-11e5-9a19-b5781644a213.jpg)

Ever closer haha

**Comment by kirbyfan64** [comment]
Dang it! SO CLOSE! Try this:

```xml
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.default.props" />
  <PropertyGroup>
    <ConfigurationType>StaticLibrary</ConfigurationType>
    <PlatformToolset>v140</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ItemGroup>
    <ClCompile Include="src-library/*.cpp">
      <AdditionalIncludeDirectories>include</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="include/MidiFile.h" />
    <ClInclude Include="include/MidiEvent.h" />
    <ClInclude Include="include/MidiMessage.h" />
    <ClInclude Include="include/MidiEventList.h" />
    <ClInclude Include="include/Binasc.h" />  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Targets" />
</Project>
```

**Comment by hardwiredstudios** [comment]
DISCO! Yeah that was it :) thank you so much for your patience and help :)

so what do i need to do now the library is built?

Can i delete the midifile.vcxproj file now?

**Comment by kirbyfan64** [comment]
1. You can add the library; see http://stackoverflow.com/questions/10049640/linking-a-static-library-to-my-project-on-visual-studio-2010
2. You can delete `midifile.vcxproj`, but I would recommended leaving it. That way, if you ever need to rebuild Midifile, you can just run `set PLATFORM=` and `msbuild`!

**Comment by hardwiredstudios** [comment]
Hey Ryan. well searching through the midifile directory, allthough it seems to build properly last night, there is no new file libmidifile.a or in fact anywhere on my laptop. Its bizarre..

**Comment by kirbyfan64** [comment]
It's actually going to generate midifile.lib. My bad...

**Comment by hardwiredstudios** [comment]
ah ok cool. Well i found it but its in the Debug folder. Is that right?

Do i just link the library with #pragma "midifile/Debug/midifile.lib" or something like that?

**Comment by kirbyfan64** [comment]
1. Yes, that's the file.
2. See http://stackoverflow.com/questions/10049640/linking-a-static-library-to-my-project-on-visual-studio-2010 for how to properly add the library.

**Comment by hardwiredstudios** [comment]
Hey Ryan, ok i added the Debug folder to my project as per this walkthrough:

http://www.steptools.com/support/stdev_docs/help/settings_vc11.html

So on Linker >> Input: I added midifile.lib to the list..
On Linker >> General: I added the midifile/Debug/ folder

...but now i get these errors when compiling:
```C++
Severity	Code	Description	Project	File	Line
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj	SPMA - Assignment 1 - 4591930 EPM	C:\Users\Paul\Desktop\Uni Stuff - YEAR 2\SOFTWARE PROGRAMMING\Assignments\Assignment 1\SPMA - Assignment 1 - 4591930 EPM\midifile.lib(Binasc.obj)	1
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Main.obj	SPMA - Assignment 1 - 4591930 EPM	C:\Users\Paul\Desktop\Uni Stuff - YEAR 2\SOFTWARE PROGRAMMING\Assignments\Assignment 1\SPMA - Assignment 1 - 4591930 EPM\midifile.lib(MidiMessage.obj)	1
```

Sorry for bugging you with this. I've only started C++ since september last year and never added files or libraries to a project so i don't know exactly what i'm doing..

**Comment by kirbyfan64** [comment]
It's fine! You're pretty much 10 steps ahead of me when I was still learning C++. ;)

Try running `msbuild /p:configuration=debug` instead of just `msbuild`. On Windows, if your application is being built in debug mode, everything else does, too.

**Comment by hardwiredstudios** [comment]
I tried that and now get this on vs command prompt:

![msbuild command prompt for vs 2015 - fail6](https://cloud.githubusercontent.com/assets/16420301/12079860/66af8b02-b240-11e5-9d70-113a5f560f13.jpg)

**Comment by kirbyfan64** [comment]
You still need to run `set PLATFORM=` first!

**Comment by hardwiredstudios** [comment]
Hey Ryan, sorry for the late reply. That sorted it. Thank you so much for all your help on this one.

Ironically, when i got back to uni and showed my lecturer, he did something really simple and got it working so its all linked. I do have a few questions now on the code itself but that's another advenure haha and i may well post a new thread on it if i can't get it sussed.

Again, thank you so much :)

Paul..

**Comment by craigsapp** [comment]
Thanks for the commentary on how to build in Visual Studio!  I don't use it, if you haven't guessed (the `make` command I refer to is for using with GNU gcc compiler in unix environments)—at least not since Visual Studio 6 :-P.  I created a [visual-studio](https://github.com/craigsapp/midifile/tree/master/visual-studio) directory/folder to make it easier for Windows users to compile the midifile library.
