### ISSUE TITLE
Undefined References

### ISSUE THREAD

**Issue by Kyle-Ueckert** [craigsapp/midifile#108]
Hi,
I am experiencing an issue where any attempt to create an instance of type Options results in an error of: 
                               undefined reference to `smf::Options::~Options()' 

I am operating on windows 11, g++ compiler, include directory paths are correct

My apologies if this is not the correct place to discuss this issue. Any corrective measures or suggestions would be greatly appreciated, thanks!

**Comment by wherefree** [comment]
您好，您所发送的邮件我已收到。

**Comment by Kyle-Ueckert** [comment]
Had to compile all files at the same time.
