### ISSUE TITLE
cmake fails looking for midicater.cpp

### ISSUE THREAD

**Issue by mjaal** [craigsapp/midifile#109]
There is a discrepancy between CMakeLists.txt and the source code in tools - midicater.cpp in CMakeLists.txt and midicat.cpp in tools, which of course causes cmake to fail: CMake Error at CMakeLists.txt:88 (add_executable):
  No SOURCES given to target: midicater

**Comment by wherefree** [comment]
您好，您所发送的邮件我已收到。

**Comment by craigsapp** [comment]
I just changed the name of the program from midicater to midicat on Friday, so I will update the cmake script to fix that.

**Comment by craigsapp** [comment]
Commit https://github.com/craigsapp/midifile/commit/6b316685301dbe2da3ce24de8ce41ede7cbb576f should fix the problem.

I added a script to run in [tools/.makeCmake](https://github.com/craigsapp/midifile/blob/master/tools/.makeCmake)  to update the example programs in `CMakeLists.txt` whenever a new program is added or renamed.

There are also additional newer programs added to the cmake script (blue lines in image below):

<img width="1260" alt="Screenshot 2024-02-04 at 17 09 34" src="https://github.com/craigsapp/midifile/assets/3487289/9c22a48f-1310-47c1-a59c-11a21de39023">
