### ISSUE TITLE
Can't compile the visual-studio project

### ISSUE THREAD

**Issue by joelpp** [craigsapp/midifile#21]
Hi! I have VS2015, and in the developer prompt when i type 

set "PLATFORM=" and "msbuild" I get the following:

> 
> C:\Users\Joel\Downloads\craigsapp-midifile-55a68db>cd visual-studio
> 
> C:\Users\Joel\Downloads\craigsapp-midifile-55a68db\visual-studio>set "PLATFORM="
> 
> C:\Users\Joel\Downloads\craigsapp-midifile-55a68db\visual-studio>msbuild
> Microsoft (R) Build Engine version 14.0.23107.0
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 2016-03-07 13:15:43.
> The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x8 6)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the pr oject, and will be ignored.
> The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program F iles (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist
> in the project, and will be ignored.
> The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x8 6)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project , and will be ignored.
> The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x8 6)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project , and will be ignored.
> The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files
> (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and
> will be ignored.
> Project "C:\Users\Joel\Downloads\craigsapp-midifile-55a68db\visual-studio\midifile.vcxproj" on node  1 (default targets).
> InitializeBuildStatus:
>   Creating "Debug\midifile.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> FinalizeBuildStatus:
>   Deleting file "Debug\midifile.tlog\unsuccessfulbuild".
>   Touching "Debug\midifile.tlog\midifile.lastbuildstate".
> Done Building Project "C:\Users\Joel\Downloads\craigsapp-midifile-55a68db\visual-studio\midifile.vc xproj" (default targets).
> 
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 

I'm not getting anything useful out of it :( Thanks!

**Comment by ZirconiumHacker** [comment]
> Build succeeded.
Are you sure it doesn't compile?  Looks like just a warning to me.  Seems to me that this issue is not an issue, unless you are referring to the warnings about _your_ computer's setup issues (see how it references Program Files?).

**Comment by craigsapp** [comment]
Some day I might try to compile in Visual Studio so that I can answer such questions...  It has been a while so perhaps time to close the issue.
