### ISSUE TITLE
Suggest two new "is" tests - Key and Time Signatures 

### ISSUE THREAD

**Issue by Linwood-F** [craigsapp/midifile#35]
I found I could use two more boolean tests, one for key signature and one for time signature, and added following the layout of the others, and offer the code if it is useful (PR following in a moment).

**Comment by craigsapp** [comment]
Agreed, and I have added these helper functions independently just recently before reading through the pull requests...

https://github.com/craigsapp/midifile/blob/00d29084dbec0dcf071206bed6053041c7da3fb1/include/MidiMessage.h#L125-L136

These seem to be identical to the PR for these functions:

https://github.com/Linwood-F/midifile/blob/d16f0f50aba80751260497a6c93d7ee10c03c471/src-library/MidiMessage.cpp#L491-L527

```cpp
//////////////////////////////
//
// MidiMessage::isTimeSignature -- Returns true if message is a meta message
//      describing Time Signature (meta message type 0x58).
//

int MidiMessage::isTimeSignature(void) const {
   if (!isMetaMessage()) {
      return 0;
   } else if ((*this)[1] != 0x58) {
      return 0;
   } else if (size() != 7) {
      // Meta time signature message can only be 7 bytes long.
      return 0;
   } else {
      return 1;
   }
}

//////////////////////////////
//
// MidiMessage::isKeySignature -- Returns true if message is a meta message
//      describing Key Signature (meta message type 0x59).
//

int MidiMessage::isKeySignature(void) const {
   if (!isMetaMessage()) {
      return 0;
   } else if ((*this)[1] != 0x59) {
      return 0;
   } else if (size() != 5) {
      // Meta key signature message can only be 5 bytes long.
      return 0;
   } else {
      return 1;
   }
}
```

https://github.com/craigsapp/midifile/blob/00d29084dbec0dcf071206bed6053041c7da3fb1/src-library/MidiMessage.cpp#L606-L648
