### ISSUE TITLE
Binasc.h missing two required headers for it to compile with MinGW

### ISSUE THREAD

**Issue by artcfox** [craigsapp/midifile#38]
Unless these includes are added to Binasc.h:

```cpp
#include <cstdlib>
#include <stdlib.h>
```
Then you get compile errors like this:

```cpp
src-library/Binasc.cpp:1273:53: error: 'atof' was not declared in this scope
       double doubleOutput = atof(&word[quoteIndex+1]);

src-library/Binasc.cpp:1307:52: error: 'atoi' was not declared in this scope
          long tempLong = atoi(&word[quoteIndex + 1]);

src-library/Binasc.cpp:1445:61: error: 'strtol' was not declared in this scope
    outputByte = (uchar)strtol(word.c_str(), (char**)NULL, 16);

src-library/Binasc.cpp:1677:40: error: 'strtod' was not declared in this scope
    double value = strtod(&word[1], NULL);
```

**Comment by craigsapp** [comment]
Looks good:

<img width="575" alt="screen shot 2017-03-06 at 1 24 54 pm" src="https://cloud.githubusercontent.com/assets/3487289/23630528/5273e206-0270-11e7-869b-9c261da24418.png">

**Comment by artcfox** [comment]
Thanks, but

#include <stdlib.h>

is required for the strtol and strtod functions, as documented here:

http://man7.org/linux/man-pages/man3/strtol.3.html
http://man7.org/linux/man-pages/man3/strtod.3.html

(and by the fact that it doesn't compile for me without #include <stdlib.h>)

**Comment by craigsapp** [comment]
Thanks,

I have added the two lines to `include/Binasc.h`:

```cpp
#include <cstdlib>
#include <stdlib.h>
```

Are you sure both are needed?  They seem to be the same include (one in C-style and the other in C++-style).  In any case, they are not causing me compiling probably in non-MinGW when both are included.

I haven't checked by compiling in MinGW yet, but should be ok now.
