### ISSUE TITLE
Receiving `reset` message > 1 byte

### ISSUE THREAD

**Issue by dpacbach** [craigsapp/midifile#67]
When reading in midi files (tested with various midi files from various different sources) and then looking at the individual messages from the MidiEvent object there always seems to be a few messages such as:

`ff  51  03  07  a1  20`

in particular at the start of the file, but my understanding is that a 0xff status byte means "reset" and should not be followed by any other bytes in the message (and sure enough, when I send the midi event to a softsynth it complains that it can't parse it).  Is this a problem with the midifile library?  Thanks

**Comment by craigsapp** [comment]
MIDI commands that start with `FF` in MIDI files are special cases.  They are called "meta" messages.  These messages should not be sent down the MIDI cable to a synthesizer, as they are not part of the MIDI protocol.  `FF` is a MIDI command called "system reset", and as you note, it has no data parameters following it:
    https://www.midi.org/specifications-old/item/table-2-expanded-messages-list-status-bytes

As a standard MIDI file meta-message, however, `ff 51 03 07 a1 20` is a tempo change.  `FF` means a meta-message (in a MIDI file, not in the MIDI protocol), and 51 (hex) is the message type.  The message has three bytes of data parameters (03 is the number of bytes to follow). and `07 a1 20` is the number of microseconds per beat (in big-endian hex): 500000 microseconds, or 0.5 seconds, which is a tempo of 120 quarter notes per minute.  The tempo is not interesting for the synthesizer, but rather it is used to control speed of the ticks/pulses used for time in the MIDI file for sending the MIDI bytes to the synthesizer.

So, if you are using the MidiFile library to send MIDI data to a synthesizer, you will have to suppress sending any message that has the first byte being `FF` in the MIDI file.

Here are other common meta messages:

<img width="908" alt="Screen Shot 2019-05-25 at 10 49 25 PM" src="https://user-images.githubusercontent.com/3487289/58378017-78a19280-7f40-11e9-97d2-314482f49ead.png">
<img width="896" alt="Screen Shot 2019-05-25 at 10 49 38 PM" src="https://user-images.githubusercontent.com/3487289/58378020-82c39100-7f40-11e9-8697-ca296efe5826.png">

**Comment by dpacbach** [comment]
Thanks, that was very helpful.  Do I understand correctly that, in the case of the "tempo change" message above for example, that I could just ignore it altogether because the MidiFile library will give me the proper timings of events anyway so that I don't have to care explicitly about tempo?

**Comment by craigsapp** [comment]
Yes, if you call `MidiFile::doTimeAnalysis()`, the `MidiEvent::second` value will contain the time in seconds that the event should be sent to the synthesizer, and this value is aware of the tempo changes in meta messages.  If you make any changes to the tempo messages, then re-running `doTimeAnalysis()` again will update the timings.

**Comment by dpacbach** [comment]
Thanks again
