### ISSUE TITLE
Website issue: Should be git clone not git pull

### ISSUE THREAD

**Issue by mount2010** [craigsapp/midifile#72]
Git pull is for getting the repository *if you already have the repository*. Git **clone**, on the other hand, fetches the repository from Github.

**Comment by mount2010** [comment]
I see that your README has a more accurate guide. Consider updating the website with the README's content?

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/craigsapp/midifile/commit/41f64e170f2e8721c24ad1ce9b4bf3e31466984e

And yes, I need to review the website documentation.  Issue https://github.com/craigsapp/midifile/issues/43 is for reminding to do that...
