### ISSUE TITLE
Docs on MidiEvent class refer to '.time' public variable, which doesn't exist 

### ISSUE THREAD

**Issue by brittanyb** [craigsapp/midifile#8]
http://midifile.sapp.org/class/MidiEvent/ 

The `.time` public variable doesn't seem to exist. but `.tick` exists as under http://midifile.sapp.org/class/MidiFile/#addEvent

Perhaps a typo?

**Comment by craigsapp** [comment]
Yes, you are right.  Originally the `.tick` parameter of MidiEvents was called `.time`, but after I added real-time analysis in seconds, calling the tick value "`.time`" was getting confusing, so I changed it to `.tick`.
