### ISSUE TITLE
comparison of constant -1 with expression of type 'char' is always false

### ISSUE THREAD

**Issue by mgood7123** [craigsapp/midifile#81]
midifile/src/Options.cpp:1127:25: warning: result of comparison of constant -1 with expression of type 'char' is always false [-Wtautological-constant-out-of-range-compare]
```
         if (optionType == -1) {         // suppressed --options option
             ~~~~~~~~~~ ^  ~~
```

**Comment by craigsapp** [comment]
Fixed in issue https://github.com/craigsapp/midifile/commit/e427ac04d61942949b73f313171dca54dd7eea03
