### ISSUE TITLE
Please add the 'install' target

### ISSUE THREAD

**Issue by yurivict** [craigsapp/midifile#83]
Currently the project doesn't install anything.

**Comment by craigsapp** [comment]
What do you want to install?

Do you mean to copy the example programs that use the midifile library from `midifile/bin` to `/usr/local/bin`?  I am assuming in that case you are using a unix-like system?

**Comment by yurivict** [comment]
The headers, library and programs.

Also ```add_library``` should have no ```STATIC``` in it. The type of library can be decided by the user.

**Comment by craigsapp** [comment]
So you mean add to https://github.com/craigsapp/midifile/blob/master/CMakeLists.txt .

Can you submit it as a pull request?  I don't use cmake to compile, so if I add something, I might mess it up.

**Comment by yurivict** [comment]
@craigsapp 

FYI: Your recent commits broke the build:
> Cannot specify link libraries for target "midicat" which is not built by this project.

**Comment by craigsapp** [comment]
Yes, I fixed it will commit https://github.com/craigsapp/midifile/commit/50c738d97b7133a92e141bc078bc4a827388c915

where I edited the cmake file to rename the `midicater` program (but looking at the name now, maybe I should rename it `midicatter` for more proper Inglish.  If you know how to add a wildcard to include all `.cpp` programs in `midifile/tools`, that would be great.   The following files should be explicitly excluded, however:

* henonfile.cpp
* midi2hum.cpp
* peep2midi.cpp
* midiexcerpt.cpp

**Comment by yurivict** [comment]
50c738d is broken:
```
CMake Error at CMakeLists.txt:121 (target_link_libraries):
  Cannot specify link libraries for target "midicat" which is not built by
  this project.
```

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/craigsapp/midifile/commit/33cff58925fd6e266587f5c3a2834989a97a77ce

(that is one reason why a wildcard system for building a list of the demo programs would be useful).
