### ISSUE TITLE
The 'midicat' program conflicts with sndio

### ISSUE THREAD

**Issue by yurivict** [craigsapp/midifile#84]
```
Installing midifile-g20200602...
pkg-static: midifile-g20200602 conflicts with sndio-1.7.0.20201210 (installs files into the same place).  Problematic file: /usr/local/bin/midicat
*** Error code 1
```

Please consider renaming it, or better rename all programs by adding the prefix ```midifile-```.

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/craigsapp/midifile/commit/6448cfd1eca7f6759eee7634893bdc03a2cc33ea.

**Comment by craigsapp** [comment]
Another fix in commit https://github.com/craigsapp/midifile/commit/50c738d97b7133a92e141bc078bc4a827388c915

Rename `midicat` in the cmake file (better to have a wildcard for programs in the tools directory, and then filter out the ones explicitly that should not be compiled).
